import { Inter } from "next/font/google";
import { Providers } from "./Components/Helpers/Providers";
import "./globals.css";
import Header from "./Components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
